---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-pipeline
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/adityaupasani2/gitops-pipeline.git
  ref:
    branch: main

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sample-app-prod
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: gitops-pipeline
  path: ./overlays/prod
  prune: true
  wait: true
